---
  - name: Install fail2ban
    yum:
      name: fail2ban 
      state: installed

  - name: Install fail2ban-systemd
    yum:
      name: fail2ban-systemd 
      state: installed

  - name: Install sendmail
    yum:
      name: sendmail 
      state: installed
      
  - name: Enable and Start fail2ban
    systemd:
      name: fail2ban
      state: restarted
      enabled: yes
...
